name: "Black Duck Scanner"
description: "Black Duck Scanner Action"
author: "Niek Palm <niek.palm@philips.com>"
branding:
  color: green
  icon: shield

inputs:
  projectName:
    description: Blackduck project name
    required: true

  versionPrefix:
    description: Blackduck project version prefix
    required: true

  url:
    description: Blackduck url
    required: true

  token:
    description: Blackduck token
    required: true

  extraArgs:
    description: Extra arguments that will be passed to the detector
    required: false

runs:
  using: docker
  image: Dockerfile
